// <auto-generated />
using System;
using BookLocal.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLocal.Data.Migrations
{
    [DbContext(typeof(BookLocalContext))]
    [Migration("20250421081450_UpdateSekcjaCms")]
    partial class UpdateSekcjaCms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLocal.Data.Data.CMS.NapisPowitalny", b =>
                {
                    b.Property<int>("IdLoga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoga"));

                    b.Property<string>("AltText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdLoga");

                    b.ToTable("NapisPowitalny");
                });

            modelBuilder.Entity("BookLocal.Data.Data.CMS.SekcjaCms", b =>
                {
                    b.Property<int>("IdSekcji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSekcji"));

                    b.Property<string>("KluczSekcji")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedByPracownikId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSekcji");

                    b.HasIndex("LastModifiedByPracownikId");

                    b.ToTable("SekcjaCms");
                });

            modelBuilder.Entity("BookLocal.Data.Data.CMS.ZawartoscCms", b =>
                {
                    b.Property<int>("IdZawartosci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZawartosci"));

                    b.Property<DateTime>("DataModyfikacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<string>("Sekcja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SekcjaCmsId")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZawartosci");

                    b.HasIndex("PracownikId");

                    b.HasIndex("SekcjaCmsId");

                    b.ToTable("ZawartoscCms");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Adres", b =>
                {
                    b.Property<int>("IdAdresu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdresu"));

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrDomu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NrLokalu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Poczta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PracownikId")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAdresu");

                    b.HasIndex("PracownikId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Firma", b =>
                {
                    b.Property<int>("IdFirmy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFirmy"));

                    b.Property<int?>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("NIP")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGON")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("WlascicielId")
                        .HasColumnType("int");

                    b.HasKey("IdFirmy");

                    b.HasIndex("AdresId");

                    b.HasIndex("WlascicielId");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Konwersacja", b =>
                {
                    b.Property<int>("IdKonwersacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKonwersacji"));

                    b.Property<DateTime>("DataOstatniejWiadomosci")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<string>("Temat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("IdKonwersacji");

                    b.HasIndex("PracownikId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Konwersacja");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Opinia", b =>
                {
                    b.Property<int>("IdOpinii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpinii"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<int?>("OcenianyPracownikId")
                        .HasColumnType("int");

                    b.Property<int?>("RezerwacjaId")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("IdOpinii");

                    b.HasIndex("OcenianyPracownikId");

                    b.HasIndex("RezerwacjaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Opinia");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Pensja", b =>
                {
                    b.Property<int>("IdPensjii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPensjii"));

                    b.Property<DateTime>("DataUtworzeniaZapisu")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataWyplaty")
                        .HasColumnType("date");

                    b.Property<decimal>("KwotaPodstawowa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("OkresDo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("OkresOd")
                        .HasColumnType("date");

                    b.Property<decimal>("Potracenia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<decimal>("Premia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StatusWyplaty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZarzadzajacyPrzedsiębiorcaId")
                        .HasColumnType("int");

                    b.HasKey("IdPensjii");

                    b.HasIndex("PracownikId");

                    b.HasIndex("ZarzadzajacyPrzedsiębiorcaId");

                    b.ToTable("Pensja");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", b =>
                {
                    b.Property<int>("IdPracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPracownika"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit");

                    b.Property<string>("EmailKontaktowy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Stanowisko")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonKontaktowy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZdjecieUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdPracownika");

                    b.HasIndex("FirmaId");

                    b.ToTable("Pracownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", b =>
                {
                    b.Property<int>("IdPrzedsiebiorcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrzedsiebiorcy"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdPrzedsiebiorcy");

                    b.ToTable("Przedsiebiorca");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Rezerwacja", b =>
                {
                    b.Property<int>("IdRezerwacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRezerwacji"));

                    b.Property<DateTime>("DataRezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImieKlienta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NazwiskoKlienta")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("ObslugujacyPrzedsiębiorcaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SzczegolyUslugiId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonKlienta")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int?>("WykonujacyPracownikId")
                        .HasColumnType("int");

                    b.HasKey("IdRezerwacji");

                    b.HasIndex("ObslugujacyPrzedsiębiorcaId");

                    b.HasIndex("SzczegolyUslugiId");

                    b.HasIndex("UzytkownikId");

                    b.HasIndex("WykonujacyPracownikId");

                    b.ToTable("Rezerwacja");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.SzczegolyUslugi", b =>
                {
                    b.Property<int>("IdSzczegolowUslugi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSzczegolowUslugi"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CzasTrwaniaMinuty")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.HasKey("IdSzczegolowUslugi");

                    b.HasIndex("PracownikId");

                    b.HasIndex("UslugaId");

                    b.ToTable("SzczegolyUslugi");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.TransakcjaRozliczeniowa", b =>
                {
                    b.Property<int>("IdTransakcji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransakcji"));

                    b.Property<DateTime?>("DataOstatniejZmianyStatusu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KwotaBrutto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("KwotaNettoDlaPracownika")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProwizjaFirmy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProwizjaPlatformy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("RezerwacjaId")
                        .HasColumnType("int");

                    b.Property<string>("StatusRozliczenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZatwierdzajacyPrzedsiębiorcaId")
                        .HasColumnType("int");

                    b.HasKey("IdTransakcji");

                    b.HasIndex("PracownikId");

                    b.HasIndex("RezerwacjaId");

                    b.HasIndex("ZatwierdzajacyPrzedsiębiorcaId");

                    b.ToTable("TransakcjaRozliczeniowa");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Usluga", b =>
                {
                    b.Property<int>("IdUslugi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUslugi"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZdjecieUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdUslugi");

                    b.ToTable("Usluga");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUzytkownika"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("TelefonKontaktowy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUzytkownika");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Wiadomosc", b =>
                {
                    b.Property<int>("IdWiadomosci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWiadomosci"));

                    b.Property<bool>("CzyOdczytana")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataOdczytania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWyslania")
                        .HasColumnType("datetime2");

                    b.Property<int>("KonwersacjaId")
                        .HasColumnType("int");

                    b.Property<int?>("NadawcaPrzedsiębiorcaId")
                        .HasColumnType("int");

                    b.Property<int?>("NadawcaUzytkownikId")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWiadomosci");

                    b.HasIndex("KonwersacjaId");

                    b.HasIndex("NadawcaPrzedsiębiorcaId");

                    b.HasIndex("NadawcaUzytkownikId");

                    b.ToTable("Wiadomosc");
                });

            modelBuilder.Entity("BookLocal.Data.Data.CMS.SekcjaCms", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "LastModifiedByPracownik")
                        .WithMany()
                        .HasForeignKey("LastModifiedByPracownikId");

                    b.Navigation("LastModifiedByPracownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.CMS.ZawartoscCms", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "Autor")
                        .WithMany()
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLocal.Data.Data.CMS.SekcjaCms", "SekcjaPowiazana")
                        .WithMany("PowiazaneZawartosci")
                        .HasForeignKey("SekcjaCmsId");

                    b.Navigation("Autor");

                    b.Navigation("SekcjaPowiazana");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Adres", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "Pracownik")
                        .WithMany("Adresy")
                        .HasForeignKey("PracownikId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", "Uzytkownik")
                        .WithMany("Adresy")
                        .HasForeignKey("UzytkownikId");

                    b.Navigation("Pracownik");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Firma", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Adres", "GlownyAdres")
                        .WithMany()
                        .HasForeignKey("AdresId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", "Wlasciciel")
                        .WithMany("ZarzadzaneFirmy")
                        .HasForeignKey("WlascicielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlownyAdres");

                    b.Navigation("Wlasciciel");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Konwersacja", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "Pracownik")
                        .WithMany("Konwersacje")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", "Uzytkownik")
                        .WithMany("Konwersacje")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Opinia", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "OcenianyPracownik")
                        .WithMany("OtrzymaneOpinie")
                        .HasForeignKey("OcenianyPracownikId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Rezerwacja", "Rezerwacja")
                        .WithMany()
                        .HasForeignKey("RezerwacjaId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", "Uzytkownik")
                        .WithMany("WystawioneOpinie")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcenianyPracownik");

                    b.Navigation("Rezerwacja");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Pensja", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "Pracownik")
                        .WithMany("WyplatyPensji")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", "ZarzadzajacyPrzedsiębiorca")
                        .WithMany()
                        .HasForeignKey("ZarzadzajacyPrzedsiębiorcaId");

                    b.Navigation("Pracownik");

                    b.Navigation("ZarzadzajacyPrzedsiębiorca");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Firma", "Firma")
                        .WithMany("Pracownicy")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Rezerwacja", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", "ObslugujacyPrzedsiębiorca")
                        .WithMany()
                        .HasForeignKey("ObslugujacyPrzedsiębiorcaId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.SzczegolyUslugi", "SzczegolyUslugi")
                        .WithMany()
                        .HasForeignKey("SzczegolyUslugiId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", "Uzytkownik")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("UzytkownikId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "WykonujacyPracownik")
                        .WithMany("WykonaneRezerwacje")
                        .HasForeignKey("WykonujacyPracownikId");

                    b.Navigation("ObslugujacyPrzedsiębiorca");

                    b.Navigation("SzczegolyUslugi");

                    b.Navigation("Uzytkownik");

                    b.Navigation("WykonujacyPracownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.SzczegolyUslugi", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "Pracownik")
                        .WithMany("OferowaneUslugiSzczegoly")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Usluga", "Usluga")
                        .WithMany("Szczegoly")
                        .HasForeignKey("UslugaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");

                    b.Navigation("Usluga");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.TransakcjaRozliczeniowa", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", "Pracownik")
                        .WithMany("TransakcjeRozliczeniowe")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Rezerwacja", "Rezerwacja")
                        .WithMany()
                        .HasForeignKey("RezerwacjaId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", "ZatwierdzajacyPrzedsiębiorca")
                        .WithMany()
                        .HasForeignKey("ZatwierdzajacyPrzedsiębiorcaId");

                    b.Navigation("Pracownik");

                    b.Navigation("Rezerwacja");

                    b.Navigation("ZatwierdzajacyPrzedsiębiorca");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Wiadomosc", b =>
                {
                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Konwersacja", "Konwersacja")
                        .WithMany("Wiadomosci")
                        .HasForeignKey("KonwersacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", "NadawcaPrzedsiębiorca")
                        .WithMany("WyslaneWiadomosci")
                        .HasForeignKey("NadawcaPrzedsiębiorcaId");

                    b.HasOne("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", "NadawcaUzytkownik")
                        .WithMany()
                        .HasForeignKey("NadawcaUzytkownikId");

                    b.Navigation("Konwersacja");

                    b.Navigation("NadawcaPrzedsiębiorca");

                    b.Navigation("NadawcaUzytkownik");
                });

            modelBuilder.Entity("BookLocal.Data.Data.CMS.SekcjaCms", b =>
                {
                    b.Navigation("PowiazaneZawartosci");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Firma", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Konwersacja", b =>
                {
                    b.Navigation("Wiadomosci");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Pracownik", b =>
                {
                    b.Navigation("Adresy");

                    b.Navigation("Konwersacje");

                    b.Navigation("OferowaneUslugiSzczegoly");

                    b.Navigation("OtrzymaneOpinie");

                    b.Navigation("TransakcjeRozliczeniowe");

                    b.Navigation("WykonaneRezerwacje");

                    b.Navigation("WyplatyPensji");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Przedsiebiorca", b =>
                {
                    b.Navigation("WyslaneWiadomosci");

                    b.Navigation("ZarzadzaneFirmy");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Usluga", b =>
                {
                    b.Navigation("Szczegoly");
                });

            modelBuilder.Entity("BookLocal.Data.Data.PlatformaInternetowa.Uzytkownik", b =>
                {
                    b.Navigation("Adresy");

                    b.Navigation("Konwersacje");

                    b.Navigation("Rezerwacje");

                    b.Navigation("WystawioneOpinie");
                });
#pragma warning restore 612, 618
        }
    }
}
